In [19]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
import spacy
import re
import pandas as pd
import matplotlib.pyplot as plt

<h3>Load Data</h3>

In [3]:
bbc_data = pd.read_csv("bbc_news.csv")

In [4]:
bbc_data.head()

   Unnamed: 0  ...                                        description
0           0  ...  With much of the UK enduring another period of...
1           1  ...  The UK's political chaos has been watched arou...
2           2  ...  Scoraig in the north west Highlands has long h...
3           3  ...  Wealthy Russians sanctioned by the US, EU and ...
4           4  ...  A quick look back at the Queen's 70 years on t...

[5 rows x 7 columns]

In [6]:
bbc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   object
 3   pubDate      1000 non-null   object
 4   guid         1000 non-null   object
 5   link         1000 non-null   object
 6   description  1000 non-null   object
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [7]:
titles = pd.DataFrame(bbc_data['title'])
titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

<h3>Clean Data</h3>

In [10]:
#lowercase-> stopwords remove  -> punctuation remove -> tokenize -> lemmatize

In [9]:
#lowercase
titles['lowercase'] = titles['title'].str.lower()
titles.head()

                                               title                                          lowercase
0                              Can I refuse to work?                              can i refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...  'liz truss the brief?' world reacts to uk poli...
2  Rationing energy is nothing new for off-grid c...  rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...  the hunt for superyachts of sanctioned russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...  platinum jubilee: 70 years of the queen in 70 ...

In [11]:
#stopwords remove
en_stopwords = stopwords.words("english")
titles['no_stopwords'] = titles['lowercase'].apply(lambda x : ' '.join([word for word in x.split() if word not in en_stopwords]))
titles.head()

                                               title  ...                                       no_stopwords
0                              Can I refuse to work?  ...                                       refuse work?
1  'Liz Truss the Brief?' World reacts to UK poli...  ...  'liz truss brief?' world reacts uk political t...
2  Rationing energy is nothing new for off-grid c...  ...    rationing energy nothing new off-grid community
3  The hunt for superyachts of sanctioned Russian...  ...      hunt superyachts sanctioned russian oligarchs
4  Platinum Jubilee: 70 years of the Queen in 70 ...  ...        platinum jubilee: 70 years queen 70 seconds

[5 rows x 3 columns]

In [13]:
#punc remove
titles['no_stop_punc'] = titles['no_stopwords'].apply(lambda x : re.sub(r"([^\w\s])","", x))
titles['no_stop_punc']

0                                            refuse work
1      liz truss brief world reacts uk political turmoil
2         rationing energy nothing new offgrid community
3          hunt superyachts sanctioned russian oligarchs
4             platinum jubilee 70 years queen 70 seconds
                             ...
995    dominic raab third senior civil servant gives ...
996                   highlights radacanu beats uytvanck
997          pictures mountain bikers descend snowy peak
998    companies must help cut living costs says new ...
999        beware online car sale scams consumers warned
Name: no_stop_punc, Length: 1000, dtype: object

In [20]:
#tokenize
titles['tokenize_clean'] = titles.apply(lambda x : word_tokenize(x['no_stop_punc']), axis=1)
titles['tokenize_raw'] = titles.apply(lambda x : word_tokenize(x['title']), axis=1)
titles['tokenize_clean']

0                                         [refuse, work]
1      [liz, truss, brief, world, reacts, uk, politic...
2      [rationing, energy, nothing, new, offgrid, com...
3      [hunt, superyachts, sanctioned, russian, oliga...
4      [platinum, jubilee, 70, years, queen, 70, seco...
                             ...
995    [dominic, raab, third, senior, civil, servant,...
996              [highlights, radacanu, beats, uytvanck]
997    [pictures, mountain, bikers, descend, snowy, p...
998    [companies, must, help, cut, living, costs, sa...
999    [beware, online, car, sale, scams, consumers, ...
Name: tokenize_clean, Length: 1000, dtype: object

In [29]:
#lemmatizer
lematizer = WordNetLemmatizer()
titles['token_clean_lemmatized'] = titles['tokenize_clean'].apply(lambda tokens : [lematizer.lemmatize(token) for token in tokens])
titles.head()

                                               title  ...                             token_clean_lemmatized
0                              Can I refuse to work?  ...                                     [refuse, work]
1  'Liz Truss the Brief?' World reacts to UK poli...  ...  [liz, truss, brief, world, reacts, uk, politic...
2  Rationing energy is nothing new for off-grid c...  ...  [rationing, energy, nothing, new, offgrid, com...
3  The hunt for superyachts of sanctioned Russian...  ...  [hunt, superyachts, sanctioned, russian, oliga...
4  Platinum Jubilee: 70 years of the Queen in 70 ...  ...   [platinum, jubilee, 70, year, queen, 70, second]

[5 rows x 9 columns]

In [30]:
tokens_raw_list = sum(titles['tokenize_raw'],[])
tokens_clean_list = sum(titles['token_clean_lemmatized'],[])

<h3>Pos Tagging</h3>

In [31]:
nlp = spacy.load("en_core_web_sm")

In [32]:
spacy_doc = nlp(' '.join(tokens_raw_list))

In [35]:
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token': token.text, 'pos_tag': token.pos_}])], ignore_index=True)

In [46]:
pos_df_count = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by="counts", ascending=False)
pos_df_count

          token pos_tag  counts
95            :   PUNCT     543
8             '   PUNCT     300
2897         in     ADP     187
4082         to    PART     175
3268         of     ADP     172
...         ...     ...     ...
2304  crumbling    VERB       1
2305     crunch   PROPN       1
827      Jarrod   PROPN       1
826    Japanese     ADJ       1
0             !   PUNCT       1

[4368 rows x 3 columns]

In [47]:
nouns = pos_df_count[pos_df_count.pos_tag == "NOUN"][:10]
nouns

       token pos_tag  counts
4267     war    NOUN      35
3552  record    NOUN      15
3416  police    NOUN      14
4356    year    NOUN      14
4316     win    NOUN      14
3061  living    NOUN      13
4009     tax    NOUN      13
2326     day    NOUN      12
3368  people    NOUN      12
2031    boss    NOUN      11

In [48]:
verbs = pos_df_count[pos_df_count.pos_tag == "VERB"][:10]
verbs

       token pos_tag  counts
3687    says    VERB      30
9          '    VERB      14
2670   found    VERB      13
4317     win    VERB      12
4324    wins    VERB      10
2713     get    VERB       9
2388    dies    VERB       9
3990    take    VERB       8
2982  killed    VERB       8
3686     say    VERB       8

<h3>NER</h3>

In [52]:
ner_df = pd.DataFrame(columns=['token','ner_tag'])

In [53]:
for token in spacy_doc.ents:
    if pd.isna(token.label_) is False:
        ner_df = pd.concat([ner_df, pd.DataFrame.from_records([{'token': token.text, 'ner_tag': token.label_}])], ignore_index=True)
ner_df

                  token   ner_tag
0             Liz Truss    PERSON
1                    UK       GPE
2             Rationing   PRODUCT
3           superyachts  CARDINAL
4               Russian      NORP
...                 ...       ...
1665    Frenkie de Jong    PERSON
1666  Manchester United    PERSON
1667          Barcelona       GPE
1668       Dominic Raab    PERSON
1669              Third   ORDINAL

[1670 rows x 2 columns]

In [55]:
ner_df_count = ner_df.groupby(['token', 'ner_tag']).size().reset_index(name="counts")
ner_df_count

                        token      ner_tag  counts
0            ' How England 's  WORK_OF_ART       1
1     ' The Papers : Voters '  WORK_OF_ART       1
2               ' World Cup :        EVENT       1
3                         '99         DATE       1
4                      'Bring  WORK_OF_ART       1
...                       ...          ...     ...
1109                    weeks         DATE       1
1110                   winter         DATE       3
1111                     year         DATE       2
1112                    years         DATE       1
1113                     zero     CARDINAL       2

[1114 rows x 3 columns]